name: SOL HMM Bot

#on:
#  workflow_dispatch:
#  schedule:
   # # تشغيل كل 15 دقيقة تقريبًا (GitHub لا يضمن الدقة)
 #   - cron: "2,17,32,47 * * * *"

#jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # =====================
      # Checkout repository
      # =====================
      - name: Checkout repo
        uses: actions/checkout@v4

      # =====================
      # Python setup
      # =====================
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # =====================
      # Install dependencies
      # =====================
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # =====================
      # Run bot with secrets
      # =====================
      - name: Run app
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python app.py
